---
title: "Getting and Cleaning Data Peer Review Project Codebook"
output: html_document
---

## R Markdown

##Getting and Cleaning Data Peer Review Project Codebook

##Identifying Variables:
"subject"                                                
"activity_type"                                         

##Measures
# In order that they appear in the tidy dataset

"timebodyaccelerometer.mean...X"                         
"timebodyaccelerometer.mean...Y"                        
"timebodyaccelerometer.mean...Z"                         
"timegravityaccelerometer.mean...X"                     
"timegravityaccelerometer.mean...Y"                      
"timegravityaccelerometer.mean...Z"                     
"timebodyaccelerometerJerk.mean...X"                     
"timebodyaccelerometerJerk.mean...Y"                    
"timebodyaccelerometerJerk.mean...Z"                     
"timebodygyroscope.mean...X"                            
"timebodygyroscope.mean...Y"                             
"timebodygyroscope.mean...Z"                            
"timebodygyroscopeJerk.mean...X"                         
"timebodygyroscopeJerk.mean...Y"                        
"timebodygyroscopeJerk.mean...Z"                         
"timebodyaccelerometermagnitude.mean.."                 
"timegravityaccelerometermagnitude.mean.."               
"timebodyaccelerometerJerkmagnitude.mean.."             
"timebodygyroscopemagnitude.mean.."                      
"timebodygyroscopeJerkmagnitude.mean.."                 
"frequencybodyaccelerometer.mean...X"                    
"frequencybodyaccelerometer.mean...Y"                   
"frequencybodyaccelerometer.mean...Z"                    
"frequencybodyaccelerometer.meanFreq...X"               
"frequencybodyaccelerometer.meanFreq...Y"                
"frequencybodyaccelerometer.meanFreq...Z"               
"frequencybodyaccelerometerJerk.mean...X"                
"frequencybodyaccelerometerJerk.mean...Y"               
"frequencybodyaccelerometerJerk.mean...Z"                
"frequencybodyaccelerometerJerk.meanFreq...X"           
"frequencybodyaccelerometerJerk.meanFreq...Y"            
"frequencybodyaccelerometerJerk.meanFreq...Z"           
"frequencybodygyroscope.mean...X"                        
"frequencybodygyroscope.mean...Y"                       
"frequencybodygyroscope.mean...Z"                        
"frequencybodygyroscope.meanFreq...X"                   
"frequencybodygyroscope.meanFreq...Y"                    
"frequencybodygyroscope.meanFreq...Z"                   
"frequencybodyaccelerometermagnitude.mean.."             
"frequencybodyaccelerometermagnitude.meanFreq.."        
"frequencybodybodyaccelerometerJerkmagnitude.mean.."     
"frequencybodybodyaccelerometerJerkmagnitude.meanFreq.."
"frequencybodybodygyroscopemagnitude.mean.."             
"frequencybodybodygyroscopemagnitude.meanFreq.."        
"frequencybodybodygyroscopeJerkmagnitude.mean.."         
"frequencybodybodygyroscopeJerkmagnitude.meanFreq.."    
"angle.tbodyaccelerometerMean.gravity."                  
"angle.tbodyaccelerometerJerkMean..gravityMean."        
"angle.tbodygyroscopeMean.gravityMean."                  
"angle.tbodygyroscopeJerkMean.gravityMean."             
"angle.X.gravityMean."                                   
"angle.Y.gravityMean."                                  
"angle.Z.gravityMean."                                   
"timebodyaccelerometer.std...X"                         
"timebodyaccelerometer.std...Y"                          
"timebodyaccelerometer.std...Z"                         
"timegravityaccelerometer.std...X"                       
"timegravityaccelerometer.std...Y"                      
"timegravityaccelerometer.std...Z"                       
"timebodyaccelerometerJerk.std...X"                     
"timebodyaccelerometerJerk.std...Y"                      
"timebodyaccelerometerJerk.std...Z"                     
"timebodygyroscope.std...X"                              
"timebodygyroscope.std...Y"                             
"timebodygyroscope.std...Z"                              
"timebodygyroscopeJerk.std...X"                         
"timebodygyroscopeJerk.std...Y"                          
"timebodygyroscopeJerk.std...Z"                         
"timebodyaccelerometermagnitude.std.."                   
"timegravityaccelerometermagnitude.std.."               
"timebodyaccelerometerJerkmagnitude.std.."               
"timebodygyroscopemagnitude.std.."                      
"timebodygyroscopeJerkmagnitude.std.."                   
"frequencybodyaccelerometer.std...X"                    
"frequencybodyaccelerometer.std...Y"                     
"frequencybodyaccelerometer.std...Z"                    
"frequencybodyaccelerometerJerk.std...X"                 
"frequencybodyaccelerometerJerk.std...Y"                
"frequencybodyaccelerometerJerk.std...Z"                 
"frequencybodygyroscope.std...X"                        
"frequencybodygyroscope.std...Y"                         
"frequencybodygyroscope.std...Z"                        
"frequencybodyaccelerometermagnitude.std.."              
"frequencybodybodyaccelerometerJerkmagnitude.std.."     
"frequencybodybodygyroscopemagnitude.std.."              
"frequencybodybodygyroscopeJerkmagnitude.std.."